
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:80" # ホストの8080ポートをコンテナの80ポートにマッピング
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      # LaravelのAPP_KEYを.envから読み込む
      APP_KEY: ${APP_KEY}

  db:
    image: mysql:8.0.40
    container_name: laravel-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
